"""add account lockout columns

Revision ID: 03882f504818
Revises: 20260520_item_creation_token
Create Date: 2026-06-10 22:14:16.625640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03882f504818'
down_revision = '20260520_item_creation_token'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
