"""Add requires_approval to Circle and create CircleJoinRequest table

Revision ID: 08171ff1f87d
Revises: 
Create Date: 2024-11-14 12:17:22.220702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08171ff1f87d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('circle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('circle_join_requests')
    # ### end Alembic commands ###
