"""Add UserWebLink model for social media links

Revision ID: 1ebeb481e638
Revises: ba9f5a2b7c1e
Create Date: 2025-09-27 12:54:26.482196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebeb481e638'
down_revision = 'ba9f5a2b7c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_web_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('display_order >= 1 AND display_order <= 5'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'display_order')
    )
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))

    op.drop_table('user_web_links')
    # ### end Alembic commands ###
