"""Fix Circle and User relationship with back_populates

Revision ID: 32750aea1d74
Revises: 466e38317778
Create Date: 2024-11-07 10:34:55.416574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32750aea1d74'
down_revision = '466e38317778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
