"""Add loan_request_id to Message model

Revision ID: 3534c409a73c
Revises: 08171ff1f87d
Create Date: 2024-11-22 08:42:06.340771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3534c409a73c'
down_revision = '08171ff1f87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_request_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_request', ['loan_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_request_id')

    # ### end Alembic commands ###
