"""Add giveaway fields to Item model and create GiveawayInterest table

Revision ID: 38c76b8e01c6
Revises: b7b770cddce5
Create Date: 2026-01-07 21:38:44.063298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c76b8e01c6'
down_revision = 'b7b770cddce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaway_interest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_giveaway_interest_item_user')
    )
    with op.batch_alter_table('admin_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_action_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_action_timestamp'))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_giveaway', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('giveaway_visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('claim_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('claimed_by_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['claimed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_web_links', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_web_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed_by_id')
        batch_op.drop_column('claim_status')
        batch_op.drop_column('giveaway_visibility')
        batch_op.drop_column('is_giveaway')

    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))

    with op.batch_alter_table('admin_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_admin_action_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_admin_user_id'), ['admin_user_id'], unique=False)

    op.drop_table('giveaway_interest')
    # ### end Alembic commands ###
