"""Add vacation_mode field to User model

Revision ID: 3f86ee6e761e
Revises: 38c76b8e01c6
Create Date: 2026-01-30 04:28:55.043816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f86ee6e761e'
down_revision = '38c76b8e01c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaway_interest', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacation_mode', sa.Boolean(), nullable=False, server_default='false'))
        # Add index for vacation_mode since it's frequently used in WHERE clauses
        batch_op.create_index('ix_users_vacation_mode', ['vacation_mode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_vacation_mode')
        batch_op.drop_column('vacation_mode')

    with op.batch_alter_table('giveaway_interest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
