"""Add Circle model and circles blueprint

Revision ID: 466e38317778
Revises: 77a81cc20b7c
Create Date: 2024-11-07 10:28:46.452932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466e38317778'
down_revision = '77a81cc20b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'circle_id')
    )
    op.drop_table('circle_memberships')
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('requires_approval')

    op.create_table('circle_memberships',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('circle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.id'], name='circle_memberships_circle_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='circle_memberships_user_id_fkey')
    )
    op.drop_table('circle_members')
    # ### end Alembic commands ###
