"""Add password reset fields

Revision ID: 98934159c704
Revises: bda3cec214d9
Create Date: 2025-06-01 21:57:18.824927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98934159c704'
down_revision = 'bda3cec214d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
