"""Add indexes to Item, Tag, and Category searchable fields

Revision ID: be0dc70326af
Revises: 916dcd3461f2
Create Date: 2024-11-07 14:05:31.334853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0dc70326af'
down_revision = '916dcd3461f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_name'))
        batch_op.create_unique_constraint('tag_name_key', ['name'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_unique_constraint('category_name_key', ['name'])

    # ### end Alembic commands ###
