"""Remove address fields from users table

Revision ID: f6a8553521db
Revises: d2ecbcc30611
Create Date: 2025-08-31 11:28:16.417872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a8553521db'
down_revision = 'd2ecbcc30611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('street')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), nullable=False, server_default='USA'))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
